### ISSUE TITLE
3.4.4 no longer available

### ISSUE THREAD

**Issue by bmrobin** [StevenClontz/bootstrap-sass-only#3]
why was the 3.4.4 release removed? i was using this version as a dependency since at least mid 2015 without any issues, and recently i noticed the bower install command failing to resolve the version on github. after looking around, i see that it was downgraded in july to 3.3.6.

i don't mind downgrading (i will verify none of my styles are affected), but i'm just concerned that this happened randomly and without notice. i would like to continue using this library as a dependency, but i am hesitant to rely on something that downgrades for seemingly no reason.

**Comment by StevenClontz** [comment]
Heya, I owe you an apology. (Not just because I didn't respond to this sooner; I've just returned from traveling for about two weeks.)

The latest version of Bootstrap is 3.3.7: http://getbootstrap.com/ I wanted to keep my releases tied to the official bootstrap versioning so there's no confusion.

So, why did I have a 3.4.4 release previously? My guess is that this release was actually based on Bootstrap's 3.2.4, but I'm not certain. So, my theory is that I made a stupid typo. I was asked in #2 to update to 3.3.6, and this was when I realized the error. In order to fix semantic versioning to actually point to the latest update of Bootstrap, I dropped the erroneous 3.4.4 tag.

If you want, you can point to the commit which the erroneous 3.4.4 tag used to point to: 6c8502a2d46448fa17dccaa1ed4b89b01e4c71f5

Full disclosure: I'm working full-time as a mathematics professor these days and have abandoned the startup I used to work on when I created this project, so I have a lot less time for webdev. I'm happy to keep this repo updated for the community, and will do so at my earliest convenience as I get issues informing me of new versions of Bootstrap core, but I may be a bit behind. I'm happy to take pull requests as well.
